routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UmumController@index')->name('index');
Route::get('/profil', 'UmumController@profil')->name('profil');
Route::get('/sejarah', 'UmumController@sejarah')->name('sejarah');
Route::get('/pengurus', 'UmumController@pengurus')->name('pengurus');
Route::get('/kontak', 'UmumController@kontak')->name('kontak');
Route::get('/berita', 'UmumController@berita')->name('berita');
Route::get('/berita/{judul}', 'UmumController@detailberita')->name('detail-berita');
Route::get('/donasi', 'UmumController@donasi')->name('donasi');
Route::get('/donasi-sekarang/{id}', 'UmumController@sekarang')->name('donasi-sekarang');
Route::get('/konfirmasi-transfer/{id}', 'UmumController@konfirmasi')->name('konfirmasi-transfer');
Route::get('/kegiatan/{id}', 'UmumController@kegiatan')->name('kegiatan');
Route::get('/laporan-wakaf', 'UmumController@laporan_wakaf')->name('laporan-wakaf');
Route::get('/detail-laporan-wakaf-{id}', 'UmumController@detail_laporan_wakaf')->name('detail-laporan-wakaf');
Route::get('/laporan-infaq', 'UmumController@laporan_infaq')->name('laporan-infaq');

Route::post('/masuk', 'UmumController@masuk')->name('masuk');

Auth::routes();
Route::get('/getTipe', 'HomeController@getTipe')->name('getTipe');
Route::get('/home', 'HomeController@index')->name('home');


Route::get('/pengajuan-transfer', 'HomeController@pengajuan_transfer')->name('pengajuan-transfer');
Route::post('/pengajuan-transfer', 'HomeController@pengajuan_transfer')->name('pengajuan-transfer');
Route::get('/getTransfer', 'HomeController@getTransfer')->name('getTransfer');
Route::get('/proses-pengajuan-transfer/{id}', 'HomeController@proses_pengajuan_transfer')->name('proses-pengajuan-transfer');

Route::get('/keluar', 'HomeController@keluar')->name('keluar');
//ADMIN
Route::get('/data-user', 'AdminController@datauser')->name('data-user');
Route::get('/add-user', 'AdminController@adduser')->name('add-user');
Route::post('/add-user', 'AdminController@adduser')->name('add-user');
Route::get('/edit-user{id}', 'AdminController@edituser')->name('edit-user');
Route::get('/nonaktif-user{id}', 'AdminController@nonaktifuser')->name('nonaktif-user');
Route::get('/aktif-user{id}', 'AdminController@aktifuser')->name('aktif-user');
Route::get('/galang-dana', 'AdminController@galang_dana')->name('galang-dana');
Route::post('/galang-dana', 'AdminController@galang_dana')->name('galang-dana');
Route::get('/berita-baru', 'AdminController@berita_baru')->name('berita-baru');
Route::post('/berita-baru', 'AdminController@berita_baru')->name('berita-baru');
Route::get('/input-laporan', 'HomeController@input_laporan')->name('input-laporan');
Route::get('/edit-wakaf{id}', 'AdminController@edit_wakaf')->name('edit-wakaf');
Route::post('/input-laporan', 'HomeController@input_laporan')->name('input-laporan');
Route::post('/upload-kegiatan', 'AdminController@upload_kegiatan')->name('upload-kegiatan');
Route::get('/add-pengurus', 'AdminController@add_pengurus')->name('add-pengurus');
Route::post('/add-pengurus', 'AdminController@add_pengurus')->name('add-pengurus');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','tipe_user_id','aktif'
    ];

				public function userTipe(){
					return $this->belongsTo('App\TipeUser','tipe_user_id');
				}
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\TipeUser;
use App\KonfirmasiTransfer;
use App\Laporan;
use DB;
use Log;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('user.welcome');
				}
				public function datauser(Request $request){
					$users = User::get();
					return view('user.data_user',compact('users'));
				}
				public function getTipe(){
						$data = TipeUser::get();
						return response()->json([
							'code'=>200,
							'message'=>'TipeUser',
							'data'=>$data
						]);
				}
				public function pengajuan_transfer(Request $request){
					if ($request->ids && $request->action == 'proses') {
						$cek = KonfirmasiTransfer::where('id',$request->ids)->where('status_transfer_id',1)->first();
						if ($cek) {
							DB::beginTransaction();
							try {
								$proses = KonfirmasiTransfer::where('id',$request->ids)->where('status_transfer_id',1)->first();
								$proses->status_transfer_id = 2;
								$proses->update();
								$laporan = Laporan::create([
									'campaign_id'=>$proses->campaign_id,
									'nama'=>$proses->nama,
									'jumlah_paket'=>$proses->jml_pkt,
									'admin'=>$request->user()->id
								]);
							} catch (\Throwable $th) {
								DB::rollback();
								return response()->json([
									'code'=>400,
									'title'=>'Gagal',
									'icon'=>'error',
									'message'=>'Gagal Diproses'
								]);
							}
							DB::commit();
							return response()->json([
								'code'=>200,
								'title'=>'Berhasil',
								'icon'=>'success',
								'message'=>'Berhasil Diproses'
							]);
							

						}
						return response()->json([
							'code'=>400,
							'title'=>'Gagal',
							'icon'=>'error',
							'message'=>'Data Tidak Ditemukan'
						]);
					}elseif ($request->ids && $request->action == 'batal') {
						$cek = KonfirmasiTransfer::where('id',$request->ids)->where('status_transfer_id',1)->first();
						if ($cek) {
							DB::beginTransaction();
							try {
								$proses = KonfirmasiTransfer::where('id',$request->ids)->where('status_transfer_id',1)->first();
								$proses->status_transfer_id = 3;
								$proses->update();
							} catch (\Throwable $th) {
								DB::rollback();
								return response()->json([
									'code'=>400,
									'title'=>'Gagal',
									'icon'=>'error',
									'message'=>'Gagal dibatalkan'
								]);
							}
							DB::commit();
							return response()->json([
								'code'=>200,
								'title'=>'Berhasil',
								'icon'=>'success',
								'message'=>'Berhasil dibatalkan'
							]);
							

						}
						return response()->json([
							'code'=>400,
							'title'=>'Gagal',
							'icon'=>'error',
							'message'=>'Data Tidak Ditemukan'
						]);
					}
					return view('user.konfirmasi_donasi');
				}
				public function getTransfer(Request $request){
					$data = KonfirmasiTransfer::get();
					$dt = [];
					foreach ($data as $key => $value) {
						$dt[] = [
							'id'=>$value->id,
							'campaign_id'=>$value->campaignId->judul,
							'tanggal'=>date('d M Y H:i', strtotime($value->created_at)),
							'nama'=>$value->nama,
							'nohp'=>$value->nohp,
							'jml_pkt'=>$value->jml_pkt,
							'pesan'=>$value->pesan,
							'bukti_transfer'=>url('assets/images/bukti').'/'.$value->bukti_transfer,
							'status'=>$value->statusTransfer->status,
							'status_transfer_id'=>$value->status_transfer_id
						];
					}
					return response()->json([
						'code'=>200,
						'data'=>$dt
					]);
				}
				public function proses_pengajuan_transfer($id){
					$datas = KonfirmasiTransfer::where('id',$id)->where('status_transfer_id','=',1)->first();
					if ($datas) {
						$datas->status_transfer_id = 2;
						$datas->update();
					}

				}
				public function input_laporan(Request $request){
					if ($request->captcha && $request->action =='add') {
						$rules = ['captcha' => 'required|captcha_api:'. request('key') . ',flat'];
						$validator = validator()->make(request()->all(), $rules);
								if ($validator->fails()) {
									return response()->json([
										'code'=>400,
										'title'=>'Oops...',
										'icon'=>'error',
										'message'=>'Code Captcha Salah',
									]);
								}else {
									$add = Laporan::create([
										'campaign_id'=>$request->campaign_id,
										'nama'=>$request->nama,
										'jumlah_paket'=>$request->jumlah_paket,
										'admin'=>$request->user()->id,
										'aktif'=>1
									]);
									if ($add) {
										return response()->json([
											'code'=>200,
											'title'=>'Berhasil',
											'icon'=>'success',
											'message'=>'Input Laporan Berhasil'
										]);
									}
									return response()->json([
										'code'=>400,
										'title'=>'Gagal',
										'icon'=>'error',
										'message'=>'Input Laporan Gagal'
									]);
								}
					}elseif ($request->captcha && $request->action =='edit') {
						$rules = ['captcha' => 'required|captcha_api:'. request('key') . ',flat'];
						$validator = validator()->make(request()->all(), $rules);
								if ($validator->fails()) {
									return response()->json([
										'code'=>400,
										'title'=>'Oops...',
										'icon'=>'error',
										'message'=>'Code Captcha Salah',
									]);
								}else {
									$add = Laporan::find($request->ids)->update([
										'campaign_id'=>$request->campaign_id,
										'nama'=>$request->nama,
										'jumlah_paket'=>$request->jumlah_paket,
										'admin'=>$request->user()->id
									]);
									if ($add) {
										return response()->json([
											'code'=>200,
											'title'=>'Berhasil',
											'icon'=>'success',
											'message'=>'Update Laporan Berhasil'
										]);
									}
									return response()->json([
										'code'=>400,
										'title'=>'Gagal',
										'icon'=>'error',
										'message'=>'Update Laporan Gagal'
									]);
								}
					}elseif ($request->action =='hapus') {
						$add = Laporan::find($request->ids)->update([
							'aktif'=>0,
							'admin'=>$request->user()->id
						]);
						if ($add) {
							return response()->json([
								'code'=>200,
								'title'=>'Berhasil',
								'icon'=>'success',
								'message'=>'Hapus Laporan Berhasil'
							]);
						}
						return response()->json([
							'code'=>400,
							'title'=>'Gagal',
							'icon'=>'error',
							'message'=>'Hapus Laporan Gagal'
						]);
					}
					return view('user.input_laporan');
				}
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    //
}

resources/views/user/add_berita.blade.php
@extends('layouts.app')
@section('css')
<meta name="_token" id="token" value="{{csrf_token()}}">
<style>
table {
  border: 1px solid #ccc;
  border-collapse: collapse;
  margin: 0;
  padding: 0;
  width: 100%;
  table-layout: fixed;
}

table caption {
  font-size: 1.5em;
  margin: .5em 0 .75em;
}

table tr {
  background-color: #f8f8f8;
  border: 1px solid #ddd;
  padding: .35em;
}

table th,
table td {
  padding: .625em;
  text-align: left;
}

table th {
  font-size: .85em;
  letter-spacing: .1em;
  text-transform: uppercase;
}
</style>
@endsection
@section('content')
<section>
            <div class="gap remove-bottom black-layer2 opc85">
                <div class="fixed-bg" style="background-image: url(../assets/images/parallax8.jpg);"></div>
                <div class="container">
                    <div class="page-title-wrap">
                        <h2>Form Berita</h2>
                        <ul class="breadcrumbs">
                            <li><a href="#" title="">Beranda</a></li>
                            <li>Form Berita</li>
                        </ul>
                    </div><!-- Page Title Wrap -->
                </div>
            </div>
        </section>
        <section>
            <div class="gap remove-gap">
                <div class="container">
                    <div class="expns-wrp remove-ext3">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-lg-12">
                                <div class="expns-box">
                                    
                                    <div class="expns-info">
																																	
																																								<div class="container">
                    <div class="sec-title text-center">
                        <div class="sec-title-inner">
                            <!-- <span>Have Question</span> -->
                            <h5>Form Berita</h5>
                        </div>
                    </div>
                    <div class="contact-form text-center">
                        <form action="#" id="konfirmasi">
                            <div class="row mrg20">
                                
                                
                                <div class="col-md-12 col-sm-12 col-lg-12">
																																<input type="text" v-model="bukti" class="thm-btn" onclick="document.getElementById('getFile').click()" placeholder="Gambar Ukuran 860 x 600" >																																
  																														<input type='file' id="getFile" accept="image/jpeg" style="display:none" @change=uploadImage>
                                </div>
																																<div class="col-md-12 col-sm-12 col-lg-12">
																																<input type="text" v-model="judul" placeholder="Judul">     
                                </div>
                                <div class="col-md-12 col-sm-12 col-lg-12">
                                    <textarea v-model="isi" placeholder="Isi"></textarea>
                                </div>
																																<div class="col-md-12 col-sm-12 col-lg-12">
																																<img
																																		:src="imgCaptcha"
																																		alt=""
																																>
																																<input
																																		v-model="captcha"
																																		placeholder="Koda Captcha. . . . . . . . . . . . . . . . . ."
																																		type="text"
																																		class="form-control mt-2"
																																>
                                </div>
																																<div class="col-md-12 col-sm-12 col-lg-12">
																																
																																				<br><br>
                                    <a class="thm-btn brd-rd40" href="#" @click="checkForm()">SIMPAN BERITA</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
@endsection
@section('js')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/vue@2.5.6/dist/vue.js"></script>
<script>
var konfirmasi = new Vue({
	el:"#konfirmasi",
	data: {
			judul:'',
			bukti:'',
			foto:'',
			isi:'',
			captcha:'',
			imgCaptcha:'',
			key:''
	},
	mounted() {
		this.refreshCaptcha()
	},
	methods: {
		async refreshCaptcha () {
			let urlcaptcha = "<?php echo url('api/get-captcha/flat'); ?>";
					await axios.get(urlcaptcha).then((response) =>{
							this.imgCaptcha = response.data.img
							this.key = response.data.key
							Swal.close()									
					},(response)=>{
									swal("Gagal!", "GAGAL", "error");
									Swal.close()
					});      
    },
		uploadImage(e){
						const image = e.target.files[0];
						const reader = new FileReader();
						reader.readAsDataURL(image);
						reader.onload = e =>{
										this.bukti = 'Foto Terisi';
										this.foto = e.target.result;
						};
		},
		loading(text){
			Swal.fire({
									title: 'Mohon menunggu...',
									text:text,
									allowEscapeKey: false,
									allowOutsideClick: false,
									background: '#FFFFFF',
									showConfirmButton: false,
									onOpen: ()=>{
													Swal.showLoading();
									}
					}).then((dismiss) => {
						// Swal.showLoading();
						}
				);
		},
		async checkForm() {
				this.loading('Sedang dikirim...');
				if (this.judul.length < 3) {
						swal("Opss...", "Judul Wajib diisi.", "error");
						Swal.close()
				}else if (!this.foto) {
						swal("Opss...", "Foto harus diisi. ", "error");
						Swal.close()
				}else if (this.isi.length < 10) {
						swal("Opss...", "Isi minimal 10 karakter", "error");
						Swal.close()
				}else if (this.captcha.length < 6) {
						swal("Opss...", "Captcha minimal 6 karakter. ", "error");
						Swal.close()
				}else{
					this.refreshCaptcha()
					let url = "<?php echo route('berita-baru'); ?>";
					let request = {judul:this.judul, gambar:this.foto, isi:this.isi, captcha : this.captcha, key: this.key, action:'add'};
					request['token'] = document.querySelector('#token').getAttribute('value');
					await axios.post(url,request).then((response) =>{
							swal(response.data.title, response.data.message, response.data.icon);
							if (response.data.code === 200) {
								this.judul = '';
								this.isi = '';
								this.foto = '';
								this.bukti = '';
								this.captcha = '';
								window.location.href = "<?php echo route('berita'); ?>";
							}
							Swal.close()									
					},(response)=>{
									swal("Gagal!", "GAGAL", "error");
									Swal.close()
					});
				}
		},
	}
});
</script>
@endsection

resources/views/user/add_user.blade.php
@extends('layouts.app')
@section('css')
<meta name="_token" id="token" value="{{csrf_token()}}">
@endsection
@section('content')
<section>
            <div class="gap remove-bottom black-layer2 opc85">
                <div class="fixed-bg" style="background-image: url(assets/images/parallax8.jpg);"></div>
                <div class="container">
                    <div class="page-title-wrap">
                        <h2>Add User</h2>
                        <ul class="breadcrumbs">
                            <li><a href="#" title="">Beranda</a></li>
                            <li>Add User </li>
                        </ul>
                    </div><!-- Page Title Wrap -->
                </div>
            </div>
        </section>
								<section>
            <div class="gap remove-gap">
                <div class="container">
                    <div class="expns-wrp remove-ext3">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-lg-12">
                                <div class="expns-box">
                                    
                                    <div class="expns-info">
																		
																																						<div class="container">
                   
																																										<div class="contact-form text-center">
																																														<form id="add_user">
																																																		<div class="row mrg20">
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																						<input type="text" v-model="nama" placeholder="Nama" required>     
																																																						</div>
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																						<input type="email" v-model="email" placeholder="Email" required>     
																																																						</div>
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																						<input type="password" v-model="password" placeholder="Password" required>     
																																																						</div>
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																						<select v-model="selected" id="" required>
																																																							<option value="">Akses Sebagai</option>
																																																							<option :value="item.id" v-for="(item, index) in options" :key="index">@{{item.tipe}}</option>
																																																						
																																																						</select>   
																																																						</div>
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																										<br><br>
																																																										<a class="thm-btn brd-rd40" @click="checkForm()">SIMPAN</a>
																																																						</div>
																																																		</div>
																																														</form>
																																										</div>
																																						</div>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
@endsection
@section('js')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/vue@2.5.6/dist/vue.js"></script>
<script>
var add_user = new Vue({
	el:"#add_user",
	data: {
		nama:'',
			email:'',
			password:'',
			selected:'',
			options:[]
	},
	mounted() {
		this.load()
	},
	methods: {
		async load () {
			let urloptions = "<?php echo route('getTipe'); ?>";
					await axios.get(urloptions).then((response) =>{
							this.options = response.data.data
							Swal.close()									
					},(response)=>{
									swal("Gagal!", "GAGAL", "error");
									Swal.close()
					});      
    },
		loading(text){
			Swal.fire({
									title: 'Mohon menunggu...',
									text:text,
									allowEscapeKey: false,
									allowOutsideClick: false,
									background: '#FFFFFF',
									showConfirmButton: false,
									onOpen: ()=>{
													Swal.showLoading();
									}
					}).then((dismiss) => {
						// Swal.showLoading();
						}
				);
		},
		async checkForm() {
				this.loading('Sedang dikirim...');
				if (this.nama < 3) {
						swal("Opss...", "Nama minimal 3 Digit.", "error");
						Swal.close()
				}else if(this.email < 6) {
						swal("Opss...", "Email minimal 6 Digit ", "error");
						Swal.close()
					}else if(this.password < 6) {
						swal("Opss...", "Password minimal 6 Digit ", "error");
						Swal.close()
					}else if(!this.selected) {
						swal("Opss...", "Akses belum dipilih ", "error");
						Swal.close()
				}else{
					let url = "<?php echo route('add-user'); ?>";
					let request = {email:this.email, password: this.password, nama : this.nama, tipe: this.selected, action:'add'};
					request['token'] = document.querySelector('#token').getAttribute('value');
					await axios.post(url,request).then((response) =>{
							swal(response.data.title, response.data.message, response.data.icon);
							if (response.data.code === 200) {
								window.location.href = "<?php echo route('data-user'); ?>";
							}
							Swal.close()									
					},(response)=>{
									swal("Gagal!", "GAGAL", "error");
									Swal.close()
					});
				}
		},
	}
});
</script>
@endsection

resources/views/user/edit_user.blade.php
@extends('layouts.app')
@section('css')
<meta name="_token" id="token" value="{{csrf_token()}}">
@endsection
@section('content')
<section>
            <div class="gap remove-bottom black-layer2 opc85">
                <div class="fixed-bg" style="background-image: url(assets/images/parallax8.jpg);"></div>
                <div class="container">
                    <div class="page-title-wrap">
                        <h2>Edit User</h2>
                        <ul class="breadcrumbs">
                            <li><a href="#" title="">Beranda</a></li>
                            <li>Edit User </li>
                        </ul>
                    </div><!-- Page Title Wrap -->
                </div>
            </div>
        </section>
								<section>
            <div class="gap remove-gap">
                <div class="container">
                    <div class="expns-wrp remove-ext3">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-lg-12">
                                <div class="expns-box">
                                    
                                    <div class="expns-info">
																		
																																						<div class="container">
                   
																																										<div class="contact-form text-center">
																																														<form id="add_user">
																																																		<div class="row mrg20">
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																						<input type="text" v-model="nama" placeholder="Nama" required>     
																																																						</div>
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																						<input type="email" v-model="email" placeholder="Email" required>     
																																																						</div>
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																						<input type="password" v-model="password" placeholder="Password" required>     
																																																						</div>
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																						<select v-model="selected" id="" required>
																																																							<option value="">Akses Sebagai</option>
																																																							<option :value="item.id" v-for="(item, index) in options" :key="index">@{{item.tipe}}</option>
																																																						
																																																						</select>   
																																																						</div>
																																																						<div class="col-md-12 col-sm-12 col-lg-12">
																																																										<br><br>
																																																										<button class="thm-btn brd-rd40" @click="checkForm()">UPDATE</button>
																																																						</div>
																																																		</div>
																																														</form>
																																										</div>
																																						</div>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
@endsection
@section('js')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/vue@2.5.6/dist/vue.js"></script>
<script>
var add_user = new Vue({
	el:"#add_user",
	data: {
			id:'{{$user->id}}',
			nama:'{{$user->name}}',
			email:'{{$user->email}}',
			password:'',
			selected:'{{$user->tipe_user_id}}',
			options:[]
	},
	mounted() {
		this.load()
	},
	methods: {
		async load () {
			let urloptions = "<?php echo route('getTipe'); ?>";
					await axios.get(urloptions).then((response) =>{
							this.options = response.data.data
							Swal.close()									
					},(response)=>{
									swal("Gagal!", "GAGAL", "error");
									Swal.close()
					});      
    },
		loading(text){
			Swal.fire({
									title: 'Mohon menunggu...',
									text:text,
									allowEscapeKey: false,
									allowOutsideClick: false,
									background: '#FFFFFF',
									showConfirmButton: false,
									onOpen: ()=>{
													Swal.showLoading();
									}
					}).then((dismiss) => {
						// Swal.showLoading();
						}
				);
		},
		async checkForm() {
				this.loading('Sedang dikirim...');
				if (this.nama < 3) {
						swal("Opss...", "Nama minimal 3 Digit.", "error");
						Swal.close()
				}else if(this.email < 6) {
						swal("Opss...", "Email minimal 6 Digit ", "error");
						Swal.close()
					}else if(this.password < 6) {
						swal("Opss...", "Password minimal 6 Digit ", "error");
						Swal.close()
					}else if(!this.selected) {
						swal("Opss...", "Akses belum dipilih ", "error");
						Swal.close()
				}else{
					let url = "<?php echo route('add-user'); ?>";
					let request = {ids:this.id, email:this.email, password: this.password, nama : this.nama, tipe: this.selected, action:'edit'};
					request['token'] = document.querySelector('#token').getAttribute('value');
					await axios.post(url,request).then((response) =>{
							swal(response.data.title, response.data.message, response.data.icon);
							if (response.data.code === 200) {
								window.location.href = "<?php echo route('data-user'); ?>";
							}
							Swal.close()									
					},(response)=>{
									swal("Gagal!", "GAGAL", "error");
									Swal.close()
					});
				}
		},
	}
});
</script>
@endsection